spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: duoduo99347
    url: jdbc:mysql://localhost:3306/wiki?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:/mapper/*Mapper.xml  # 配置mapper映射文件
